# Source plugins generated by antibody
source ${HOME}/.zsh_plugins.sh

if test -f ${HOME}/.zshrc.local
then
    source ${HOME}/.zshrc.local
fi

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Enables vim mode
bindkey -v

bindkey '^a' autosuggest-accept
bindkey '^e' autosuggest-execute

bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

bindkey '^R' history-incremental-pattern-search-backward
bindkey '^P' vi-up-line-or-history
bindkey '^N' vi-down-line-or-history
